### ISSUE TITLE
Mongoose Schema for comments

### ISSUE THREAD

**Issue by coderlore** [coderlore/todo-mvc-auth-local#5]

**Comment by emtek995** [comment]
I think we will also need a schema for the replys, I did some quick testing and found that Mongoose doesn't allow a schema to have itself in it.

**Comment by emtek995** [comment]
Had an idea to just store the ids of the replies instead of the actual replies.

**Comment by JuanPabloNSZ** [comment]
Hi! I push some changes to the **'5-mongoose-schema-for-comments'** branch:
- I create the Message.js model, that has the properties: **userId, message, likes, replies**
- I did some changes to the routes, copying and pasting the modifications that @emtek995 did in his branch (routes)
- Modified the 'messages.ejs', but only to see how to render the message propierties into the dom
- I also modified the 'messages.js' from controllers (but only because this is necessary for render the messages)

**Comment by JuanPabloNSZ** [comment]
> I think we will also need a schema for the replys, I did some quick testing and found that Mongoose doesn't allow a schema to have itself in it.

The schema that I create for the **messages** has a property called 'replies', which is an array.
Maybe we could build a 'createReply' function (in the **messages.js file** (controllers folders)),
that create a new message but push all its properties into the 'replies array' of the original message.

@emtek995 Let me know what you think! 😊
